---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    # Get the environment variables from CircleCI and add to the EC2 instance
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    # These TYPEORM environment variables now point to /root/backend/dist
    - TYPEORM_ENTITIES: /root/backend/dist/modules/domain/**/*.entity.js
    - TYPEORM_MIGRATIONS: /root/backend/dist/migrations/*.js
    - TYPEORM_MIGRATIONS_DIR: /root/backend/dist/migrations
  roles:
    - deploy
