---
- name: "Extract zipped artifact into EC2 instance"
  ansible.builtin.unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Install Node modules"
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: "Start Node app"
  shell: |
    cd /home/ubuntu/backend
    pm2 stop default
    pm2 start npm -- start
