---
- name: create backend directory
  become: yes
  file:
    path: /root/backend
    state: directory
    mode: 0755

- name: copy backend files
  become: yes
  copy:
    src: /root/project/artifact.tar.gz
    dest: /root/backend/artifact.tar.gz

- name: "Extract backend into EC2 instance"
  become: yes
  shell: |
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
  args:
    chdir: /root/backend

- name: "upgrade packages"
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies"
  # See: https://knowledge.udacity.com/questions/881483
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    apt-get install -y nodejs
    apt-get install gcc g++ make -y
    npm install -g npm
    npm install -g pm2

- name: "start node app"
  become: yes
  shell: |
    echo "TYPEORM_DATABASE="${TYPEORM_DATABASE}
    cd /root/backend/dist
    pm2 stop default
    pm2 start main.js --name backend -f
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    # Get the environment variables from CircleCI and add to the EC2 instance
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    # These TYPEORM environment variables now point to /root/backend/dist
    TYPEORM_ENTITIES: /root/backend/dist/modules/domain/**/*.entity.js
    TYPEORM_MIGRATIONS: /root/backend/dist/migrations/*.js
    TYPEORM_MIGRATIONS_DIR: /root/backend/dist/migrations
