---
- name: "Extract zipped artifact into EC2 instance"
  ansible.builtin.unarchive:
    become: yes
    src: /root/project/artifact.tar.gz
    dest: /root/backend

- name: "Install Node modules"
  shell: |
    cd /root/backend
    npm install

- name: "Start Node app"
  shell: |
    cd /root/backend
    pm2 stop default
    pm2 start npm -- start
